
export const GET_WALLET_ADDRESS = "GET_WALLET_ADDRESS";
export const GET_USER_THB_BALANCE ="GET_USER_THB_BALANCE"
export const GET_USER_THB_LP_BALANCE ="GET_USER_THB_LP_BALANCE"
export const GET_USER_TAMOUNT ="GET_USER_TAMOUNT"
export const GET_USER_TAMOUNT_LP ="GET_USER_TAMOUNT_LP"
export const GET_USER_BRL ="GET_USER_BRL"
export const  GET_USER_BRL_LP ="GET_USER_BRL_LP"
export const GET_USER_MINT_BRAWL_POINTS ="GET_USER_MINT_BRAWL_POINTS"
